# Generated by Django 5.0.6 on 2024-06-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equpment_app', '0004_rename_order_details_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
    ]
