# Generated by Django 5.0.6 on 2024-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equpment_app', '0007_equpment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equpment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equpment',
            name='requres_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_to_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='approved_to_ship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='recived',
            field=models.BooleanField(default=False),
        ),
    ]
