# Generated by Django 5.0.6 on 2024-07-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equpment_app', '0008_alter_equpment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
