# Generated by Django 5.1 on 2024-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equpment_app', '0011_branch_active_supplier_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
